<?php

declare(strict_types=1);

namespace SixtyEightPublishers\Environment\Command;

use Composer\Command\BaseCommand;
use Symfony\Component\Dotenv\Dotenv;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use SixtyEightPublishers\Environment\Bootstrap\EnvBootstrap;

final class DumpEnvironmentCommand extends BaseCommand
{
	/** @var string  */
	private $rootDir;

	/**
	 * @param string      $rootDir
	 * @param string|NULL $name
	 */
	public function __construct(string $rootDir, string $name = NULL)
	{
		$this->rootDir = rtrim($rootDir, '/');

		parent::__construct($name);
	}

	/**
	 * {@inheritDoc}
	 */
	protected function configure(): void
	{
		$this->setName('environment:dump')
			->setAliases(['env:dump'])
			->setDescription('Compiles variables from .env files to .env.local.php.')
			->addArgument('env', InputArgument::REQUIRED, 'The application environment to dump .env files for - e.g. "prod".');
	}

	/**
	 * {@inheritDoc}
	 */
	protected function execute(InputInterface $input, OutputInterface $output): int
	{
		$_SERVER[EnvBootstrap::APP_ENV] = $env = $input->getArgument('env');
		$filename = $this->rootDir . '/.env';
		$variables = var_export($this->loadEnv($filename, $env), TRUE);

		$content = <<<EOT
<?php

// This file was generated by 68publishers/environment
// Run command "composer env:dump $env" to regenerate it

return $variables;

EOT;
		file_put_contents($filename.'.local.php', $content, LOCK_EX);

		$this->getIO()->writeError('An file .env.local.php has been dumped.');

		return 0;
	}

	/**
	 * @param string $path
	 * @param string $env
	 *
	 * @return array
	 */
	private function loadEnv(string $path, string $env): array
	{
		// save original variables
		$backup = [$_SERVER, $_ENV];

		unset($_SERVER[EnvBootstrap::APP_ENV]);
		$_ENV = [EnvBootstrap::APP_ENV => $env];

		// Load SYMFONY_DOTENV_VARS variable that is used by symfony/dotenv
		$_SERVER['SYMFONY_DOTENV_VARS'] = implode(',', array_keys($_SERVER));
		putenv('SYMFONY_DOTENV_VARS='.$_SERVER['SYMFONY_DOTENV_VARS']);

		try {
			(new Dotenv(FALSE))->loadEnv($path);

			unset($_ENV['SYMFONY_DOTENV_VARS']);

			$output = $_ENV;
		} finally {
			// set original variables back
			[$_SERVER, $_ENV] = $backup;
		}

		return $output ?? [];
	}
}
